"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.upload = exports.server = exports.logger = exports.environment = exports.database = exports.cache = exports.authentication = void 0;
const authentication = require("@config/authentication.config");
exports.authentication = authentication;
const cache = require("@config/cache.config");
exports.cache = cache;
const database = require("@config/database.config");
exports.database = database;
const environment = require("@config/environment.config");
exports.environment = environment;
const logger = require("@config/logger.config");
exports.logger = logger;
const server = require("@config/server.config");
exports.server = server;
const upload = require("@config/upload.config");
exports.upload = upload;
